//
//  H264.h
//
//  File generated by Magnet rest2mobile 1.1 - Mar 18, 2015 3:03:18 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "sd" : {
    "origin" : "ns3.pdl-secure",
    "height" : 360,
    "availability" : 60,
    "id" : 300615239,
    "width" : 640,
    "profile" : 112,
    "bitrate" : 566,
    "url" : "https://pdlvimeocdn-a.akamaihd.net/48754/974/300615239.mp4?token2=1426716598_e85d54f6b53e46dedcb97ae2955614f7&aksessionid=c5dc23a0b55d7ba6"
  },
  "hd" : {
    "origin" : "ns3.pdl-secure",
    "height" : 720,
    "availability" : 60,
    "id" : 300615240,
    "width" : 1280,
    "profile" : 113,
    "bitrate" : 2000,
    "url" : "https://pdlvimeocdn-a.akamaihd.net/16374/672/300615240.mp4?token2=1426716598_8beae397015e499f13d64060861ed211&aksessionid=8e7a325cc378d4b4"
  ...

*/

#import <Rest2Mobile/Rest2Mobile.h>


@class Hd;
@class Sd;

@interface H264 : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, strong) Hd *hd;


@property (nonatomic, strong) Sd *sd;



@end
