//
//  Hd.h
//
//  File generated by Magnet rest2mobile 1.1 - Mar 18, 2015 3:03:18 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "origin" : "ns3.pdl-secure",
  "height" : 720,
  "availability" : 60,
  "id" : 300615240,
  "width" : 1280,
  "profile" : 113,
  "bitrate" : 2000,
  "url" : "https://pdlvimeocdn-a.akamaihd.net/16374/672/300615240.mp4?token2=1426716598_8beae397015e499f13d64060861ed211&aksessionid=8e7a325cc378d4b4"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface Hd : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, assign) int availability;


@property (nonatomic, assign) int bitrate;


@property (nonatomic, assign) int height;


@property (nonatomic, assign) int magnetId;


@property (nonatomic, copy) NSString *origin;


@property (nonatomic, assign) int profile;


@property (nonatomic, copy) NSString *url;


@property (nonatomic, assign) int width;



@end
