//
//  Hls.h
//
//  File generated by Magnet rest2mobile 1.1 - Mar 18, 2015 3:03:18 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "all" : "https://av00vimeo-i.akamaihd.net/i/,48754/974/300615239,16374/672/300615240,.mp4.csmil/master.m3u8?primaryToken=1426716598_d12ddce3bca8f95df3fb2054673d06d8",
  "cdn" : "akamai",
  "origin" : "ns",
  "hd" : "https://av00vimeo-i.akamaihd.net/i/,16374/672/300615240,.mp4.csmil/master.m3u8?primaryToken=1426716598_89b342e80533e74fd443841a6dd0eb7b"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface Hls : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *all;


@property (nonatomic, copy) NSString *cdn;


@property (nonatomic, copy) NSString *hd;


@property (nonatomic, copy) NSString *origin;



@end
