//
//  Request.h
//
//  File generated by Magnet rest2mobile 1.1 - Mar 18, 2015 3:03:18 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "files" : {
    "hls" : {
      "all" : "https://av00vimeo-i.akamaihd.net/i/,48754/974/300615239,16374/672/300615240,.mp4.csmil/master.m3u8?primaryToken=1426716598_d12ddce3bca8f95df3fb2054673d06d8",
      "cdn" : "akamai",
      "origin" : "ns",
      "hd" : "https://av00vimeo-i.akamaihd.net/i/,16374/672/300615240,.mp4.csmil/master.m3u8?primaryToken=1426716598_89b342e80533e74fd443841a6dd0eb7b"
    },
    "h264" : {
      "sd" : {
        "origin" : "ns3.pdl-secure",
        "height" : 360,
        "availability" : 60,
        "id" : 300615239,
        "width" : 640,
        "profile" : 112,
        "bitrate" : 566,
        "url" : "https://pdlvimeocdn-a.akamaihd.net/48754/974/300615239.mp4?token2=1426716598_e85d54f6b53e46dedcb97ae2955614f7&aksessionid=c5dc23a0b55d7ba6"
      },
      "hd" : {
          ...

*/

#import <Rest2Mobile/Rest2Mobile.h>


@class Files;

@interface Request : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, strong) Files *files;



@end
