//
//  Sd.h
//
//  File generated by Magnet rest2mobile 1.1 - Mar 18, 2015 3:03:18 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "origin" : "ns3.pdl-secure",
  "height" : 360,
  "availability" : 60,
  "id" : 300615239,
  "width" : 640,
  "profile" : 112,
  "bitrate" : 566,
  "url" : "https://pdlvimeocdn-a.akamaihd.net/48754/974/300615239.mp4?token2=1426716598_e85d54f6b53e46dedcb97ae2955614f7&aksessionid=c5dc23a0b55d7ba6"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface Sd : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, assign) int availability;


@property (nonatomic, assign) int bitrate;


@property (nonatomic, assign) int height;


@property (nonatomic, assign) int magnetId;


@property (nonatomic, copy) NSString *origin;


@property (nonatomic, assign) int profile;


@property (nonatomic, copy) NSString *url;


@property (nonatomic, assign) int width;



@end
