//
//  Thumbs.h
//
//  File generated by Magnet rest2mobile 1.1 - Mar 18, 2015 3:03:18 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "640" : "https://i.vimeocdn.com/video/494016254_640.jpg",
  "960" : "https://i.vimeocdn.com/video/494016254_960.jpg",
  "base" : "https://i.vimeocdn.com/video/494016254",
  "1280" : "https://i.vimeocdn.com/video/494016254_1280.jpg"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface Thumbs : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *base;


@property (nonatomic, copy) NSString *property1280;


@property (nonatomic, copy) NSString *property640;


@property (nonatomic, copy) NSString *property960;



@end
