//
//  Video.h
//
//  File generated by Magnet rest2mobile 1.1 - Mar 18, 2015 3:03:18 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "thumbs" : {
    "640" : "https://i.vimeocdn.com/video/494016254_640.jpg",
    "960" : "https://i.vimeocdn.com/video/494016254_960.jpg",
    "base" : "https://i.vimeocdn.com/video/494016254",
    "1280" : "https://i.vimeocdn.com/video/494016254_1280.jpg"
  },
  "id" : 109933873,
  "title" : "Designed: Liz Ogbu teaser",
  "duration" : 76,
  "embed_code" : "<iframe src=\"https://player.vimeo.com/video/109933873\" width=\"500\" height=\"281\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>",
  "share_url" : "https://vimeo.com/109933873",
  "url" : "https://vimeo.com/109933873"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@class Thumbs;

@interface Video : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, assign) int duration;


@property (nonatomic, copy) NSString *embed_code;


@property (nonatomic, assign) int magnetId;


@property (nonatomic, copy) NSString *share_url;


@property (nonatomic, strong) Thumbs *thumbs;


@property (nonatomic, copy) NSString *title;


@property (nonatomic, copy) NSString *url;



@end
