//
//  VimeoVideoConfigResult.h
//
//  File generated by Magnet rest2mobile 1.1 - Mar 18, 2015 3:03:18 PM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "video" : {
    "thumbs" : {
      "640" : "https://i.vimeocdn.com/video/494016254_640.jpg",
      "960" : "https://i.vimeocdn.com/video/494016254_960.jpg",
      "base" : "https://i.vimeocdn.com/video/494016254",
      "1280" : "https://i.vimeocdn.com/video/494016254_1280.jpg"
    },
    "id" : 109933873,
    "title" : "Designed: Liz Ogbu teaser",
    "duration" : 76,
    "embed_code" : "<iframe src=\"https://player.vimeo.com/video/109933873\" width=\"500\" height=\"281\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>",
    "share_url" : "https://vimeo.com/109933873",
    "url" : "https://vimeo.com/109933873"
  },
  "request" : {
    "files" : {
      "hls" : {
        "all" : "https://av00vimeo-i.akamaihd.net/i/,48754/974/300615239,16374/672/300615240,.mp4.csmil/master.m3u8?primaryToken=1426716598_d12ddce3bca8f95df3fb2054673d06d8",
        "cdn" : "akamai",
          ...

*/

#import <Rest2Mobile/Rest2Mobile.h>


@class Request;
@class Video;

@interface VimeoVideoConfigResult : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, strong) Request *request;


@property (nonatomic, strong) Video *video;



@end
