//
//  VimeoController.h
//
//  File generated by Magnet rest2mobile 1.1 - Mar 18, 2015 3:03:18 PM
//  @See Also: http://developer.magnet.com
//
#import <Rest2Mobile/Rest2Mobile.h>
@class VimeoVideoConfigResult;

@protocol VimeoControllerProtocol <NSObject>

@optional

/**
 Generated from URL GET https://player.vimeo.com/video/{id}/config
 GET video/{id}/config
 @param magnetId(original name : id) style:TEMPLATE
 @param success The block to be executed on the completion of a successful request. This block has no return value and takes one argument: the object/primitive constructed from the response data of the request.
 @param failure The block to be executed on the completion of an unsuccessful request. This block has no return value and takes one argument: the error that occurred during the request.
 @return A 'MMCall' object.
 */
- (MMCall *)getVimeoVideoConfig:(NSString *)magnetId
                        success:(void (^)(VimeoVideoConfigResult *response))success
                        failure:(void (^)(NSError *error))failure;

@end

@interface VimeoController : MMController<VimeoControllerProtocol>

@end
